//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderingContext : DbContext
    {
        public OrderingContext()
            : base("name=OrderingContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Dish> Dish { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<MenuType> Menu_type { get; set; }
        public virtual DbSet<OrderDetails> Order_details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Site> Site_Info { get; set; }
    }
}
